site_name: Ad
theme:
  name: material
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true
            members_order: source
            show_submodules: true
nav:
  - Home: index.md
  - Environmental:
      - Overview: environmental.md
    #  - Data preprocessing: environmental-data-preprocessing.md
    #  - Hyperparameter optimization: environmental-hyperparameter-optimization.md
watch:
  - src

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js