seed: 42
data_path: "data/power_consumption_tetouan"
model_registry_path: "model_registry/environmental"
artifacts_path: "artifacts"
arduino_project_path: "src/advml_hackaton/arduino"

pretrain_epochs: 2
qat_epochs: 3
hpo_trials: 10

max_model_size_kb: 16