// Auto-generated by train_gesture_model.py
#pragma once
static const int ML_NUM_CLASSES = 4;
static const int ML_SEQ_LEN    = 4;
static const int ML_VOCAB      = 4;
static const int ML_NUM_FEATS  = 16;
static const float ML_W[ML_NUM_CLASSES][ML_NUM_FEATS] = {
  { 0.771329f, 0.000000f, -0.165257f, -0.529002f, 1.473463f, 0.000000f, -0.898295f, -0.498097f, 0.000000f, 0.771329f, -0.694259f, 0.000000f, 0.000000f, 1.599855f, 0.058954f, -1.581739f },
  { -0.982080f, 0.000000f, 1.948774f, -0.989419f, -0.107166f, 0.000000f, -0.400886f, 0.485327f, 0.000000f, -0.982080f, 0.959355f, 0.000000f, 0.000000f, -0.175007f, -1.001261f, 1.153542f },
  { 0.931435f, 0.000000f, -0.821082f, -0.186010f, -0.993416f, 0.000000f, 1.412700f, -0.494941f, 0.000000f, 0.931435f, -1.007092f, 0.000000f, 0.000000f, -1.134231f, -0.528732f, 1.587306f },
  { -0.720684f, 0.000000f, -0.962434f, 1.704431f, -0.372881f, 0.000000f, -0.113519f, 0.507712f, 0.000000f, -0.720684f, 0.741997f, 0.000000f, 0.000000f, -0.290617f, 1.471039f, -1.159110f },
};
static const float ML_B[ML_NUM_CLASSES] = { 0.343311f, -0.161831f, -0.246248f, 0.064768f };
static const char* ML_CLASS_NAMES[ML_NUM_CLASSES] = { "PURPLE", "CYAN", "WHITE", "ORANGE" };
// Token order: 0=UP  1=DOWN  2=LEFT  3=RIGHT